with-expecter: true
inpackage: true
dir: "{{.InterfaceDir}}"
outpkg: "{{.PackageName}}"

packages:
  github.com/stuttgart-things/sthings-tetris/internal/tui/components:
    interfaces:
      Stopwatch: {}
